changelog:
    exclude:
        authors:
            - dependabot
    categories:
        - title: Bugfixes
          labels:
              - bug
        - title: Features
          labels:
              - enhancement
        - title: Maintenance
          labels:
              - chore
              - documentation
        - title: Other Changes
          labels:
              - "*"
